/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiAnalyzeFoodRouteImport } from './routes/api/analyze-food'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeFoodRoute = ApiAnalyzeFoodRouteImport.update({
  id: '/api/analyze-food',
  path: '/api/analyze-food',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/diary': typeof DiaryRoute
  '/foods': typeof FoodsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/today': typeof TodayRoute
  '/api/analyze-food': typeof ApiAnalyzeFoodRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/diary': typeof DiaryRoute
  '/foods': typeof FoodsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/today': typeof TodayRoute
  '/api/analyze-food': typeof ApiAnalyzeFoodRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/diary': typeof DiaryRoute
  '/foods': typeof FoodsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/today': typeof TodayRoute
  '/api/analyze-food': typeof ApiAnalyzeFoodRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/diary'
    | '/foods'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/today'
    | '/api/analyze-food'
    | '/api/coach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/diary'
    | '/foods'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/today'
    | '/api/analyze-food'
    | '/api/coach'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coach'
    | '/diary'
    | '/foods'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/today'
    | '/api/analyze-food'
    | '/api/coach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  DiaryRoute: typeof DiaryRoute
  FoodsRoute: typeof FoodsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  TodayRoute: typeof TodayRoute
  ApiAnalyzeFoodRoute: typeof ApiAnalyzeFoodRoute
  ApiCoachRoute: typeof ApiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-food': {
      id: '/api/analyze-food'
      path: '/api/analyze-food'
      fullPath: '/api/analyze-food'
      preLoaderRoute: typeof ApiAnalyzeFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  DiaryRoute: DiaryRoute,
  FoodsRoute: FoodsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  TodayRoute: TodayRoute,
  ApiAnalyzeFoodRoute: ApiAnalyzeFoodRoute,
  ApiCoachRoute: ApiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
